version: "3.8"

services:
  springboot-service:
    image: neha676/backend:v2
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hrmsportal
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "9292:8080"
    depends_on:
      - mysql

  frontend:
    image: neha676/frontend:v2
    ports:
      - "3300:80"
    depends_on:
       springboot-service:

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hrmsportal
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
